### ISSUE TITLE
error: command 'extension.runCurrent' not found when running "Run current line'

### ISSUE THREAD

**Issue by haizop** [xijo/vscode-iterm-rspec#1]
Hello - thanks for the great extension.

When I open a spec, move the cursor to a specific line, and run `rspec-iterm: Run current line` it fails to execute the spec and an error dialog pops up, reporting `command 'extension.runCurrent'`

The other commands work just fine.

Any thoughts?

**Comment by xijo** [comment]
Just released `0.0.2` to fix that. Thanks for reporting and glad you like it :+1:

**Comment by haizop** [comment]
Awesome thanks!
